# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'PRESTO-Wallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'AMScrollingNavbar'
  pod 'MZFormSheetPresentationController', :git => 'https://github.com/JeffreyCA/MZFormSheetPresentationController'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'SwiftLint'
  pod 'SwiftMultiSelect', :git => 'https://github.com/JeffreyCA/SwiftMultiSelect.git'
  pod 'SwiftSoup'
  
  target 'PRESTO-WalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = 
'$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
