# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PRESTO-Wallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftSoup'
  pod 'SwiftLint'
  
  target 'PRESTO-WalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PRESTO-WalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
